title : Polytope Examples for DT Data Access
author: Adam Warde, James Hawkes, Alice Sartori Monteiro de Barros and Tiago Quintino
logo: 'docs/images/Logo_Destination_Earth_Colours.png'

# Short description about the book
description: >-
  Guides to accessing Destination Earth DT data via the Polytope web service hosted on the LUMI Databridge.

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  home_page_in_navbar         : true

# Interact link settings
notebook_interface            : "notebook"

# MyST parser settings
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image

# Launch button settings
repository:
  url                         : https://github.com/destination-earth-digital-twins/polytope-examples
  path_to_book                : ""

binder:
  binderhub_url               : "https://code.insula.destine.eu"
  text                        : "Launch DestinE Insula (requires login)"
