channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.12
  - pip
  - ipykernel
  - nbformat
  - nbclient
  - healpy
  - cartopy
  - matplotlib
  - netcdf4
  - numcodecs<0.16
  - numpy
  - pandas
  - pydantic
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - xgboost
  - zarr
  # - zarr>=2.18,<3
  - lxml
  - eccodes
  # - eccodes>=2.42.0
  - pip:
      - covjsonkit
      - h3
      - earthkit-data==1.2.0
      - earthkit-geo==1.1.1
      - earthkit-hydro==1.4.0
      - earthkit-meteo==1.1.0
      - earthkit-plots==1.0.3
      - earthkit-transforms==1.0.0
      - earthkit-utils==1.0.2
      - kaleido
      - polytope-client
      - python-dotenv
      - conflator
      - pip-tools
      - conda-lock
      - pytest
      - geopandas