channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - pip
  - ipykernel
  - nbformat
  - nbclient
  - healpy
  - cartopy
  - matplotlib
  - netcdf4
  - numcodecs<0.16
  - numpy
  - pandas
  - pydantic
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - xgboost
  - zarr>=2.18,<3
  - lxml
  - eccodes>=2.42.0
  - pip:
      - covjsonkit==0.2.19
      - h3
      - earthkit-plots==0.6.1
      - earthkit-data==0.19.4
      - earthkit-geo==0.5.2
      - earthkit-transforms==0.5.4
      - earthkit-regrid==0.5.1
      - kaleido==0.2.1
      - polytope-client
      - python-dotenv
      - conflator
      - pip-tools
      - conda-lock
      - pytest