channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - ipykernel
  - nbformat
  - healpy
  - pip
  - pip:
      - lxml
      - earthkit==0.13.2
      - covjsonkit>=0.2.5
      - polytope-client
      - kaleido==0.2.1
      - h3
      - rasterio
      - xgboost
      - scikit-learn
      - rioxarray
