channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - pip
  - ipykernel
  - nbformat
  - nbclient
  - healpy
  - cartopy
  - matplotlib
  - netcdf4
  - numcodecs<0.16
  - numpy
  - pandas
  - pydantic
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - xgboost
  - zarr>=2.18,<3
  - lxml
  - eccodes>=2.42.0
  - pip:
      - earthkit-data[all]>=1rc9
      - earthkit-geo[all]==1rc7
      - earthkit-hydro>=1.3rc1
      - earthkit-meteo>=1rc3
      - earthkit-plots>=1rc9
      - earthkit-transforms>=1rc5
      - earthkit-utils>=1rc1
      - covjsonkit==0.2.19
      - reverse-geocode
      - mir-python
      - h3
      - kaleido==0.2.1
      - polytope-client
      - python-dotenv
      - conflator
      - pip-tools
      - conda-lock
      - pytest